oF=eval('document.fb.sb');
sB='|Selecione uma revista#'
sB=sB+'assinar/revista-arquitetura-e-construcao/|Arquitetura & Construção#assinar/revista-aventuras-na-historia/|Aventuras na História#assinar/revista-boa-forma/|Boa Forma#assinar/revista-bravo/|Bravo!#assinar/revista-bons-fluidos/|Bons Fluidos#assinar/revista-capricho/|Capricho#assinar/revista-caras/|CARAS#assinar/revista-casa-claudia/|Casa Claudia#assinar/revista-claudia/|Claudia#assinar/colecao-70-aniversario-da-segunda-guerra-mundial/|Coleção 70º Aniversário da Segunda Guerra Mundial#assinar/colecao-atlas-national-geographic-brasil/|Coleção Atlas National Geographic#assinar/colecao-cinemateca-veja/|Coleção Cinemateca Veja#assinar/colecao-classicos-disney-para-ler-e-ouvir/|Coleção Clássicos Disney#assinar/colecao-cozinha-regional-brasileira/|Coleção Cozinha Regional Brasileira#assinar/colecao-english-way/|Coleção English Way#assinar/colecao-espanhol-si/|Coleção Español ¡Si!#assinar/colecao-grandes-compositores-da-musica-classica/|Coleção Grandes Compositores da Música Clássica#assinar/colecao-guia-veja-de-medicina-e-saude/|Coleção Guia Veja de Medicina e Saúde#assinar/colecao-historias-da-biblia-para-a-familia/|Coleção Histórias da Bíblia#assinar/revista-contigo/|Contigo!#assinar/revista-dicas-info/|Dicas Info#assinar/revista-elle/|Elle#assinar/revista-estilo-de-vida/|Estilo de Vida#assinar/revista-exame/|Exame#assinar/revista-gloss/|Gloss#assinar/revista-info/|Info#assinar/revista-manequim/|Manequim#assinar/revista-mens-health/|Men\'s Health#assinar/revista-mundo-estranho/|Mundo Estranho#assinar/revista-national-geographic-brasil/|National Geographic#assinar/revista-nova/|Nova#assinar/revista-nova-escola/|Nova Escola#assinar/revista-piaui/|piauí#assinar/revista-placar/|Placar#assinar/revista-playboy/|Playboy#assinar/revista-quatro-rodas/|Quatro Rodas#assinar/revista-recreio/|Recreio#assinar/revista-runners-world|Runner\'s World#assinar/revista-saude/|Saúde!#assinar/revista-superinteressante/|Superinteressante#assinar/revista-veja/|Veja#assinar/revista-viagem-e-turismo/|Viagem e Turismo#assinar/revista-vida-simples/|Vida Simples#assinar/revista-vip/|VIP#assinar/revista-voce-sa/|Você s/a#assinar/revista-womens-health|Women\'s Health#'
aB=sB.split('#');
for(i=0;i<(aB.length-1);i++){
aD=aB[i].split('|');
oF.length=i+1;
oF[i].value='http://www.assineabril.com.br/'+aD[0]+'origem='+ sO;
oF[i].text=aD[1];}
