
LOOMIA_C=new function(){var _1="16569";var _2="static-cache.loomia.com";var _3="static-assets.loomia.com";var _4="recs-onewidget-cache.loomia.com";var _5="recs-social.loomia.com";var _6="recs-simitems-cache.loomia.com";var _7="clickstream.loomia.com";var _8="metrics.loomia.com";var _9="recs-personal.loomia.com";var _10="recs-checkout.loomia.com";var _11="recs-onewidget.loomia.com";var _12="recs-social.loomia.com";var _13="recs-simitems.loomia.com";var _14="clickstream.loomia.com";var _15="metrics.loomia.com";var _16="recs-personal.loomia.com";var _17="recs-checkout.loomia.com";if(document.location.href.substr(0,5)=="https"){var _18="https://";var _19=_18+_3+"/";var _20=_18+_11;var _21=_18+_12;var _22=_18+_13;var _23=_18+_14;var _24=_18+_15;var _25=_18+_16;var _26=_18+_17;}else{var _18="http://";var _19=_18+_2+"/";var _20=_18+_4;var _21=_18+_5;var _22=_18+_6;var _23=_18+_7;var _24=_18+_8;var _25=_18+_9;var _26=_18+_10;}
_20=_20+"/onewidget";ONEWIDGET_SOCIAL_SERVER=_21+"/onewidget";_21=_21+"/jsapi";_22=_22+"/jsapi";_23=_23+"/jsapi";_24=_24+"/jsapi";_25=_25+"/jsapi";_26=_26+"/jsapi";PURCHASE_SERVER="https://"+_13+"/jsapi";var _27="loomia.com";var _28="";var _29=new Array(6563391702,1552386631,4054209077,1552378413,4134778195,9417631467,9057873063,1563102314,4134684359,1566934074,8273817175,1552285695,9065194741,1552378618,1552314287,1552388888,6556060014,193089694,5345243108,-6563283990,1552328218);var _30=_19+_28+"images/";var _31=_19+_28+"js/";var _22=_22;var _32=_23;var _33=_32;var _34=false;var _35=1;var _36=1;var _37=0.01;return{VERSION:_1,PROTOCOL:_18,APACHE_SERVER:_19,SOCIAL_SERVER:_21,SIMITEM_SERVER:_22,ONEWIDGET_SERVER:_20,ONEWIDGET_SOCIAL_SERVER:ONEWIDGET_SOCIAL_SERVER,CLICKSTREAM_SERVER:_23,METRICS_SERVER:_24,PERSONALIZED_SERVER:_25,CHECKOUT_SERVER:_26,RATINGS_SERVER:_32,SOCIAL_PUBKEYS:_29,TRACKING_COOKIE_DOMAIN:_27,TOP_LEVEL_PATH:_28,ZOPE_BASE_URL:_33,DEBUGGING:_34,JS_PATH:_31,METERING_VALUE:_35,PAIR_RECS_METERING_VALUE:_36,TIMING_DATA_METERING_VALUE:_37,PUID_COOKIE:"_loomiaPUID",LOOMIA_TRACKING_COOKIE:"_loomiaUTrack",LOOMIA_SESSION_COOKIE:"_loomiasession",CLIENT_TRACKING_COOKIE:"_loomiaUTrack_client",SNID_COOKIE:"_loomiasnid",OPTOUT_COOKIE:"_loomiaOO",PUB_LIST_COOKIE:"_loomiaPubs",AUTH_COOKIE:"loomiaws",PUB_LIST_DELIMITER:"@@",LOOMIA_DEMUX:"loomia_demux",COOKIE_LIST:[this.LOOMIA_TRACKING_COOKIE,this.LOOMIA_SESSION_COOKIE,this.CLIENT_TRACKING_COOKIE,this.PUID_COOKIE,this.SNID_COOKIE,this.OPTOUT_COOKIE,this.PUB_LIST_COOKIE,this.LOOMIA_DEMUX],WIDGET_PAGE:_31+"widget.html",MASTER_PAGE:_31+"master.html",DIV_ID_IN_WIDGET_PAGE:"__loomia_div__",DISPLAY_DIV:"loomia_display",CSS_TEMPLATE:_19+_28+"style/style.css",CSS_PATH:_19+_28+"style/",SKIN_PATH:_19+_28+"skins/",IMAGE_PATH:_19+_28+"images/",RATE_CONTENT_METHOD:_32+"?methodName=setRating",PURCHASE_RECORDER_METHOD:PURCHASE_SERVER+"?methodName=recordPurchase",METRICS_METHOD:_24+"?methodName=addMetrics",PERSISTENCE_MARKER:"[@@]",SEARCH_KEYWORDS_LIMIT:2};};var LOOMIA_DEBUG=new function(){var _38=LOOMIA_C.DEBUGGING;var _39=navigator.userAgent.toLowerCase();var _40={version:(_39.match(/.+(?:rv|it|ra|ie)[\/: ]([\d.]+)/)||[])[1],safari:/webkit/.test(_39),opera:/opera/.test(_39),msie:(/msie/.test(_39))&&(!/opera/.test(_39)),mozilla:(/mozilla/.test(_39))&&(!/(compatible|webkit)/.test(_39))};function timestamp(){var d=new Date();var _42=d.getHours().toString();var _43=addZero(d.getMinutes());var _44=addZero(d.getSeconds());var ms=d.getMilliseconds().toString();return _42+":"+_43+":"+_44+"."+ms;}
function addZero(t){if(t<10){return"0"+t.toString();}else{return t.toString();}}
return{browser:_40,d_alert:function(s){if(_38){alert(s);}},debugPrint:function(msg){if(_38){try{window.loadFirebugConsole();}
catch(e){}
if(window.console){window.console.log(msg);}else{alert(msg);}}else{return;}},debug:function(msg){if(!_38){return;}
var d=(new Date());var ts=""+d.getHours()+":"+d.getMinutes()+":"+d.getSeconds()+"."+d.getMilliseconds();msg=ts+" "+msg;try{window.loadFirebugConsole();}
catch(e){}
if(!(_40.msie&&_40.version<=7)&&window.console){console.log(msg);}else{try{debug_box=document.getElementById("debug_box");}
catch(e){return;}
if(!debug_box){return;}
var p=document.createElement("p");p.appendChild(document.createTextNode(timestamp()+": "+msg));debug_box.appendChild(p);}}};};var Base64={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",encode:function(_51){var _52="";var _53,chr2,chr3,enc1,enc2,enc3,enc4;var i=0;_51=Base64._utf8_encode(_51);while(i<_51.length){_53=_51.charCodeAt(i++);chr2=_51.charCodeAt(i++);chr3=_51.charCodeAt(i++);enc1=_53>>2;enc2=((_53&3)<<4)|(chr2>>4);enc3=((chr2&15)<<2)|(chr3>>6);enc4=chr3&63;if(isNaN(chr2)){enc3=enc4=64;}else{if(isNaN(chr3)){enc4=64;}}
_52=_52+this._keyStr.charAt(enc1)+this._keyStr.charAt(enc2)+this._keyStr.charAt(enc3)+this._keyStr.charAt(enc4);}
return _52;},decode:function(_55){var _56="";var _57,chr2,chr3;var _58,enc2,enc3,enc4;var i=0;_55=_55.replace(/[^A-Za-z0-9\+\/\=]/g,"");while(i<_55.length){_58=this._keyStr.indexOf(_55.charAt(i++));enc2=this._keyStr.indexOf(_55.charAt(i++));enc3=this._keyStr.indexOf(_55.charAt(i++));enc4=this._keyStr.indexOf(_55.charAt(i++));_57=(_58<<2)|(enc2>>4);chr2=((enc2&15)<<4)|(enc3>>2);chr3=((enc3&3)<<6)|enc4;_56=_56+String.fromCharCode(_57);if(enc3!=64){_56=_56+String.fromCharCode(chr2);}
if(enc4!=64){_56=_56+String.fromCharCode(chr3);}}
_56=Base64._utf8_decode(_56);return _56;},_utf8_encode:function(_59){_59=_59.replace(/\r\n/g,"\n");var _60="";for(var n=0;n<_59.length;n++){var c=_59.charCodeAt(n);if(c<128){_60+=String.fromCharCode(c);}else{if((c>127)&&(c<2048)){_60+=String.fromCharCode((c>>6)|192);_60+=String.fromCharCode((c&63)|128);}else{_60+=String.fromCharCode((c>>12)|224);_60+=String.fromCharCode(((c>>6)&63)|128);_60+=String.fromCharCode((c&63)|128);}}}
return _60;},_utf8_decode:function(_63){var _64="";var i=0;var c=c1=c2=0;while(i<_63.length){c=_63.charCodeAt(i);if(c<128){_64+=String.fromCharCode(c);i++;}else{if((c>191)&&(c<224)){c2=_63.charCodeAt(i+1);_64+=String.fromCharCode(((c&31)<<6)|(c2&63));i+=2;}else{c2=_63.charCodeAt(i+1);c3=_63.charCodeAt(i+2);_64+=String.fromCharCode(((c&15)<<12)|((c2&63)<<6)|(c3&63));i+=3;}}}
return _64;}};var LOOMIA_UTILS=new function(){var _65="16569";var _66="static-cache.loomia.com";var _67="static-assets.loomia.com";var _68="recs-onewidget-cache.loomia.com";var _69="recs-social.loomia.com";var _70="recs-simitems-cache.loomia.com";var _71="clickstream.loomia.com";var _72="metrics.loomia.com";var _73="recs-personal.loomia.com";var _74="recs-checkout.loomia.com";var _75="recs-onewidget.loomia.com";var _76="recs-social.loomia.com";var _77="recs-simitems.loomia.com";var _78="clickstream.loomia.com";var _79="metrics.loomia.com";var _80="recs-personal.loomia.com";var _81="recs-checkout.loomia.com";if(document.location.href.substr(0,5)=="https"){var _82="https://";var _83=_82+_67+"/";var _84=_82+_75;var _85=_82+_76;var _86=_82+_77;var _87=_82+_78;var _88=_82+_79;var _89=_82+_80;var _90=_82+_81;}else{var _82="http://";var _83=_82+_66+"/";var _84=_82+_68;var _85=_82+_69;var _86=_82+_70;var _87=_82+_71;var _88=_82+_72;var _89=_82+_73;var _90=_82+_74;}
_84=_84+"/onewidget";ONEWIDGET_SOCIAL_SERVER=_85+"/onewidget";_85=_85+"/jsapi";_86=_86+"/jsapi";_87=_87+"/jsapi";_88=_88+"/jsapi";_89=_89+"/jsapi";_90=_90+"/jsapi";PURCHASE_SERVER="https://"+_77+"/jsapi";var _91="loomia.com";var _92="";var _93=new Array(6563391702,1552386631,4054209077,1552378413,4134778195,9417631467,9057873063,1563102314,4134684359,1566934074,8273817175,1552285695,9065194741,1552378618,1552314287,1552388888,6556060014,193089694,5345243108,-6563283990,1552328218);var _94=_83+_92+"images/";var _95=_83+_92+"js/";var _86=_86;var _96=_87;var _97=_96;var _98=false;var _99=1;var _100=1;var _101=0.01;var _102=800;var _103=525;var _104,loomia_CheckInterval;var _105="_x_";var _106="||";var _107=2;return{name:"Loomia JS Utilities",stacktrace:function(){var s="";for(var a=arguments.caller;a!=null;a=a.caller){s+="->"+funcname(a.callee)+"\n";if(a.caller==a){s+="*";break;}}
return s;},contains:function(a,obj){if(typeof(a)!="undefined"&&a.length>0){var i=a.length;while(i--){if(a[i]===obj){return true;}}
return false;}else{return false;}},timestamp:function(){var d=(new Date());var ts=""+d.getHours()+":"+d.getMinutes()+":"+d.getSeconds()+"."+d.getMilliseconds();return ts;},debugout:function(s){LOOMIA_DEBUG.debug(s);},setCookie:function(name,_111,_112,path,_114,_115){document.cookie=name+"="+escape(_111)+((_112)?"; expires="+_112:"")+((path)?"; path="+path:"")+((_114)?"; domain="+_114:"")+((_115)?"; secure="+_115:"");},setCookieIfAbsent:function(name,_116,_117,path,_118,_119){var _120=this.getCookie(name);if(_120!=null&&_120!=""){return _120;}else{this.setCookie(name,_116,_117,path,_118,_119);return _116;}},getCookie:function(name){var arg=name+"=";var alen=arg.length;var clen=document.cookie.length;var i=0;while(i<clen){var j=i+alen;if(document.cookie.substring(i,j)==arg){return this.getCookieVal(j);}
var i=document.cookie.indexOf(" ",i)+1;if(i==0){break;}}
return"";},getCookieVal:function(_125){var _126=document.cookie.indexOf(";",_125);if(_126==-1){_126=document.cookie.length;}
return unescape(document.cookie.substring(_125,_126));},deleteCookie:function(name,path,_127){if(this.getCookie(name)){document.cookie=name+"="+((path)?"; path="+path:"")+((_127)?"; domain="+_127:"")+"; expires=Thu, 01-Jan-70 00:00:01 GMT";}},expDate:function(_128){var _129=new Date();var _130=new Date();_130.setTime(_129.getTime()+3600000*24*_128);var _131=_130.toGMTString();return _131;},useLoadingImage:function(){var _132=navigator.userAgent.toLowerCase();if(this.loomia_check("safari",_132)){return false;}else{return true;}},loomia_check:function(sub,_134){place=_134.indexOf(sub)+1;return place;},trackingCookie:function(tag){return(this.randomUsername());},randomSessionCookie:function(N){if(N==null){N=4;}
var r1=Math.random().toString().substring(2,7);var r2=Math.random().toString().substring(2,7);var _139=""+r1+r2+"_"+this.randNString(N);return _139;},randNString:function(N){var s="";for(var i=0;i<N;i++){s=s+Math.floor(Math.random()*10);}
return s;},randomUsername:function(tag){var d=new Date();var x=10000*d.getSeconds()+1000*(d.getHours()/10)+d.getMilliseconds();var r=Math.ceil(100000*Math.random());var _142=r.toString()+"_"+x.toString();if(typeof tag!="undefined"&&tag!=null){_142=_142+"_"+tag;}
return _142;},splitArray:function(_143,N){if(_143.length<=N){return _143;}
var _144=0;var _145=0;var _146=[];var _147=[];for(var i=0;i<_143.length;i++){_147[_144]=_143[i];_144++;if(_144==N){_146[_145]=_147;_145++;_144=0;var _147=[];}}
if(_144>0){_146[_145]=_147;}
return _146;},getQueryVariables:function(_148){if(!_148){_148=window.location.search.substring(1);}
var vars=_148.split("&");var _150={};for(var i=0;i<vars.length;i++){var pair=vars[i].split("=");_150[pair[0]]=pair[1];}
return _150;},csvToArray:function(_152){if(!_152){return null;}
var _153=_152.split(",");var _154=new Array();counter=0;for(var i=0;i<_153.length;i++){str=_153[i];str=str.replace(/^\s*/,"").replace(/\s*$/,"");if(str.length>0){_154[counter++]=str;}}
return _154;},fbs_share:function(){var link=location.href;var _156=document.title;var url="http://"+_69+"/fb?methodName=sswshare_dialog&link="+encodeURIComponent(link)+"&title="+encodeURIComponent(_156)+"&publisher_key="+L_VARS.publisher_key;if(L_VARS.guid&&L_VARS.guid!=""){url+="&guid="+encodeURIComponent(L_VARS.guid);}
window.open(url,"sharer","toolbar=0,status=0,width=626,height=510,resizable=1");return false;},encodeURIForFB:function(url){var _158="@@EQ@@";var benc=Base64.encode(decodeURIComponent(url));return benc.replace(/=/g,_158);},fbs_login:function(_160,_161,_162){var d=document;var _163="";if(_161){_163=_106+"publisher_key"+_105+_161;}
if(_162!=""){var f=_162;}else{var f="http://www.facebook.com/login.php?api_key="+_160+"&v=1.0&popup=true&next=?params=methodName"+_105+"sswlogin"+_163+_106+"url"+_105;}
var p="";_104=window.open(f+p,"login","toolbar=0,status=0,resizable=1,width="+_102+",height="+_103);loomia_CheckInterval=setInterval("LOOMIA_UTILS.checkPopupStatus()",200);return false;},checkPopupStatus:function(){if(_104&&_104.closed){clearInterval(loomia_CheckInterval);if(_107>0){document.location.reload();_107-=1;}}},get:function(el){return document.getElementById(el);},toggle:function(){for(var i=0,el;el=this.get(arguments[i]);i++){el.style.display=(el.style.display!="none"?"none":"");}},switchTab:function(id,_167){if(id!=_167){this.get("tab_"+id).className="selected";this.get("loomia_"+id).style.display="block";this.get("tab_"+_167).className="";this.get("loomia_"+_167).style.display="none";}
return false;},onclick_handler:function(_168){try{if(L_VARS.onclick_args){params=L_VARS.onclick_args;}else{params=_168;}
if(L_VARS.onclick_handler){L_VARS.onclick_handler(params);}
return true;}
catch(e){return true;}},obj2query:function(obj,_169,_170){if(typeof obj!="object"){return"";}
if(arguments.length==1){_169=/\.php$/.test(document.location.href);}
var rv="";for(var prop in obj){if(obj.hasOwnProperty(prop)){var _173=_170?_170+"."+prop:prop;if(obj[prop]instanceof Array){for(var i=0;i<obj[prop].length;i++){if(typeof obj[prop][i]=="object"){rv+="&"+LOOMIA_UTILS.obj2query(obj[prop][i],_169,_173);}else{rv+="&"+encodeURIComponent(_173)+(_169?"[]":"")+"="+encodeURIComponent(obj[prop][i]);}}}else{if(obj[prop]instanceof Date){rv+="&"+encodeURIComponent(_173)+"="+obj[prop].getTime();}else{if(obj[prop]instanceof Object){if(obj.toString&&obj.toString!==Object.prototype.toString){rv+="&"+encodeURIComponent(_173)+"="+encodeURIComponent(obj[prop].toString());}else{rv+="&"+LOOMIA_UTILS.obj2query(obj[prop],_169,_173);}}else{rv+="&"+encodeURIComponent(_173)+"="+encodeURIComponent(obj[prop]);}}}}}
return rv.replace(/^&/,"");},_checkForObject:function(str){if(!str){return false;}
try{myval=typeof(eval(str));if(myval!="undefined"){return true;}}
catch(e){}
return false;},_encode:function(s){for(var c,i=-1,l=(s=s.split("")).length,o=String.fromCharCode;++i<l;s[i]=(c=s[i].charCodeAt(0))>=127?o(192|(c>>>6))+o(128|(c&63)):s[i]){}
return s.join("");},_decode:function(s){for(var a,b,i=-1,l=(s=s.split("")).length,o=String.fromCharCode,c="charCodeAt";++i<l;((a=s[i][c](0))&128)&&(s[i]=(a&252)==192&&((b=s[i+1][c](0))&192)==128?o(((a&3)<<6)+(b&63)):o(128),s[++i]="")){}
return s.join("");},utf8_decode:function(s){if(document.characterSet){dcs=document.characterSet;}else{if(document.charset){dcs=document.charset;}}
if(dcs&&dcs.indexOf("8859")>-1){return Base64._utf8_decode(s);}else{return s;}},execute_when_loaded:function(func){var _176;var _177=arguments;var _178=_177[1];var _179=0;var _180;if(_177.length==3){_180=_177[2];}
function executeCheck(){LOOMIA_DEBUG.debug("Execute when loaded: Checking for "+_178);_179+=1;if(!(LOOMIA_UTILS._checkForObject(_178)||_179==_180)){if(!_176){_176=setInterval(executeCheck,50);}
return;}
clearInterval(_176);func();return;}
return executeCheck();},execute_until_loaded:function(func){var _181;var _182=arguments;var _183=_182[1];var _184=0;var _185;if(_182.length==3){_185=_182[2];}
function executeCheck(){if(LOOMIA_UTILS._checkForObject(_183)){clearInterval(_181);return;}else{if(_184==_185){clearInterval(_181);return;}else{func();}
if(!_181){_181=setInterval(executeCheck,50);}}
_184+=1;return;}
return executeCheck();},execute_when_present:function(func,_186){var temp=_186;var _188;function executeCheck(_186){var _189=document.getElementById(_186);LOOMIA_UTILS.debugout("checking for "+_186);function _ec(){executeCheck(_186);}
if(!_189){if(!_188){_188=setInterval(_ec,50);}
return;}
clearInterval(_188);func();}
executeCheck(temp);}};};function loomia_setCookie(name,_190,_191,path,_192,_193){LOOMIA_UTILS.setCookie(name,_190,_191,path,_192,_193);}
function loomia_deleteCookie(name,path,_194){LOOMIA_UTILS.deleteCookie(name,path,_194);}
function loomiaShowTab(id,_195){LOOMIA_UTILS.switchTab(id,_195);}
function loomia_toggle(id){LOOMIA_UTILS.toggle(id);}
function fbs_share(){LOOMIA_UTILS.fbs_share();}
function fbs_login(_196,_197,_198){LOOMIA_UTILS.fbs_login(_196,_197,_198);}
if(!Array.indexOf){Array.prototype.indexOf=function(obj){for(var i=0;i<this.length;i++){if(this[i]==obj){return i;}}
return-1;};}
LOOMIA_PJS=(function(){var _199="0.1.0",P,B,esc,init,empty,ec;ec=(function(){var _200="Thu, 01-Jan-1970 00:00:01 GMT",RATIO=1000*60*60*24,KEYS=["expires","path","domain"],esc=escape,un=unescape,doc=document,me;var _201=function(){var r=new Date();r.setTime(r.getTime());return r;};var _202=function(_203,_204){var i,key,val,r=[],opt=(arguments.length>2)?arguments[2]:{};r.push(esc(_203)+"="+esc(_204));for(i=0;i<KEYS.length;i++){key=KEYS[i];if(val=opt[key]){r.push(key+"="+val);}}
if(opt.secure){r.push("secure");}
return r.join("; ");};var _205=function(){var k="__EC_TEST__",v=new Date();v=v.toGMTString();this.set(k,v);this.enabled=(this.remove(k)==v);return this.enabled;};me={set:function(key,val){var opt=(arguments.length>2)?arguments[2]:{},now=_201(),expire_at,cfg={};if(opt.expires){opt.expires*=RATIO;cfg.expires=new Date(now.getTime()+opt.expires);cfg.expires=cfg.expires.toGMTString();}
var keys=["path","domain","secure"];for(i=0;i<keys.length;i++){if(opt[keys[i]]){cfg[keys[i]]=opt[keys[i]];}}
var r=_202(key,val,cfg);doc.cookie=r;return val;},has:function(key){key=esc(key);var c=doc.cookie,ofs=c.indexOf(key+"="),len=ofs+key.length+1,sub=c.substring(0,key.length);return((!ofs&&key!=sub)||ofs<0)?false:true;},get:function(key){key=esc(key);var c=doc.cookie,ofs=c.indexOf(key+"="),len=ofs+key.length+1,sub=c.substring(0,key.length),end;if((!ofs&&key!=sub)||ofs<0){return null;}
end=c.indexOf(";",len);if(end<0){end=c.length;}
return un(c.substring(len,end));},remove:function(k){var r=me.get(k),opt={expires:_200};doc.cookie=_202(k,"",opt);return r;},keys:function(){var c=doc.cookie,ps=c.split("; "),i,p,r=[];for(i=0;i<ps.length;i++){p=ps[i].split("=");r.push(un(p[0]));}
return r;},all:function(){var c=doc.cookie,ps=c.split("; "),i,p,r=[];for(i=0;i<ps.length;i++){p=ps[i].split("=");r.push([un(p[0]),un(p[1])]);}
return r;},version:"0.2.1",enabled:false};me.enabled=_205.call(me);return me;}());empty=function(){};esc=function(str){return"PS"+str.replace(/_/g,"__").replace(/ /g,"_s");};C={search_order:["localstorage","whatwg_db","globalstorage","cookie"],name_re:/^[a-z][a-z0-9_-]+$/i,methods:["init","get","set","remove","load","save"],sql:{version:"1",create:"CREATE TABLE IF NOT EXISTS persist_data (k TEXT UNIQUE NOT NULL PRIMARY KEY, v TEXT NOT NULL)",get:"SELECT v FROM persist_data WHERE k = ?",set:"INSERT INTO persist_data(k, v) VALUES (?, ?)",remove:"DELETE FROM persist_data WHERE k = ?"},flash:{div_id:"_persist_flash_wrap",id:"_persist_flash",path:"persist.swf",size:{w:1,h:1},args:{autostart:true}}};B={gears:{size:-1,test:function(){return(window.google&&window.google.gears)?true:false;},methods:{transaction:function(fn){var db=this.db;db.execute("BEGIN").close();fn.call(this,db);db.execute("COMMIT").close();},init:function(){var db;db=this.db=google.gears.factory.create("beta.database");db.open(esc(this.name));db.execute(C.sql.create).close();},get:function(key,fn,_213){var r,sql=C.sql.get;if(!fn){return;}
this.transaction(function(t){r=t.execute(sql,[key]);if(r.isValidRow()){fn.call(_213||this,true,r.field(0));}else{fn.call(_213||this,false,null);}
r.close();});},set:function(key,val,fn,_214){var _215=C.sql.remove,sql=C.sql.set,r;this.transaction(function(t){t.execute(_215,[key]).close();t.execute(sql,[key,val]).close();if(fn){fn.call(_214||this,true,val);}});},remove:function(key,fn,_216){var _217=C.sql.get;sql=C.sql.remove,r,val;this.transaction(function(t){if(fn){r=t.execute(_217,[key]);if(r.isValidRow()){val=r.field(0);t.execute(sql,[key]).close();fn.call(_216||this,true,val);}else{fn.call(_216||this,false,null);}
r.close();}else{t.execute(sql,[key]).close();}});}}},whatwg_db:{size:200*1024,test:function(){var name="PersistJS Test",desc="Persistent database test.";if(!window.openDatabase){return false;}
if(!window.openDatabase(name,C.sql.version,desc,B.whatwg_db.size)){return false;}
return true;},methods:{transaction:function(fn){if(!this.db_created){var sql=C.sql.create;this.db.transaction(function(t){t.executeSql(sql,[],function(){this.db_created=true;});},empty);}
this.db.transaction(fn);},init:function(){var desc,size;desc=this.o.about||"Persistent storage for "+this.name;size=this.o.size||B.whatwg_db.size;this.db=openDatabase(this.name,C.sql.version,desc,size);},get:function(key,fn,_220){var sql=C.sql.get;if(!fn){return;}
_220=_220||this;this.transaction(function(t){t.executeSql(sql,[key],function(t,r){if(r.rows.length>0){fn.call(_220,true,r.rows.item(0)["v"]);}else{fn.call(_220,false,null);}});});},set:function(key,val,fn,_221){var _222=C.sql.remove,sql=C.sql.set;this.transaction(function(t){t.executeSql(_222,[key],function(){t.executeSql(sql,[key,val],function(t,r){if(fn){fn.call(_221||this,true,val);}});});});return val;},remove:function(key,fn,_223){var _224=C.sql.get;sql=C.sql.remove;this.transaction(function(t){if(fn){t.executeSql(_224,[key],function(t,r){if(r.rows.length>0){var val=r.rows.item(0)["v"];t.executeSql(sql,[key],function(t,r){fn.call(_223||this,true,val);});}else{fn.call(_223||this,false,null);}});}else{t.executeSql(sql,[key]);}});}}},globalstorage:{size:5*1024*1024,test:function(){return window.globalStorage?true:false;},methods:{key:function(key){return esc(this.name)+esc(key);},init:function(){this.store=globalStorage[this.o.domain];},get:function(key,fn,_225){key=this.key(key);if(fn){fn.call(_225||this,true,this.store.getItem(key));}},set:function(key,val,fn,_226){key=this.key(key);this.store.setItem(key,val);if(fn){fn.call(_226||this,true,val);}},remove:function(key,fn,_227){var val;key=this.key(key);val=this.store[key];this.store.removeItem(key);if(fn){fn.call(_227||this,(val!==null),val);}}}},localstorage:{size:-1,test:function(){return window.localStorage?true:false;},methods:{key:function(key){return esc(this.name)+esc(key);},init:function(){this.store=localStorage;},get:function(key,fn,_228){key=this.key(key);if(fn){fn.call(_228||this,true,this.store.getItem(key));}},set:function(key,val,fn,_229){key=this.key(key);this.store.setItem(key,val);if(fn){fn.call(_229||this,true,val);}},remove:function(key,fn,_230){var val;key=this.key(key);val=this.getItem(key);this.store.removeItem(key);if(fn){fn.call(_230||this,(val!==null),val);}}}},ie:{prefix:"_persist_data-",size:64*1024,test:function(){return window.ActiveXObject?true:false;},make_userdata:function(id){var el=document.createElement("div");el.id=id;el.style.display="none";el.addBehavior("#default#userData");if(document.readyState=="interactive"||document.readyState=="complete"){document.body.appendChild(el);}
return el;},methods:{init:function(){var id=B.ie.prefix+esc(this.name);this.el=B.ie.make_userdata(id);if(this.o.defer){this.load();}},get:function(key,fn,_231){var val;key=esc(key);if(!this.o.defer){this.load();}
val=this.el.getAttribute(key);if(fn){fn.call(_231||this,val?true:false,val);}},set:function(key,val,fn,_232){key=esc(key);this.el.setAttribute(key,val);if(!this.o.defer){this.save();}
if(fn){fn.call(_232||this,true,val);}},remove:function(key,fn,_233){this.set(key,"",fn,_233);},load:function(){this.el.load(esc(this.name));},save:function(){this.el.save(esc(this.name));}}},cookie:{delim:":",size:4000,test:function(){return P.Cookie.enabled?true:false;},methods:{key:function(key){return this.name+B.cookie.delim+key;},get:function(key,val,fn,_234){key=this.key(key);val=ec.get(key);if(fn){fn.call(_234||this,val!=null,val);}},set:function(key,val,fn,_235){key=this.key(key);ec.set(key,val,this.o);if(fn){fn.call(_235||this,true,val);}},remove:function(key,val,fn,_236){var val;key=this.key(key);val=ec.remove(key);if(fn){fn.call(_236||this,val!=null,val);}}}},flash:{test:function(){if(!window.SWFObject||!deconcept||!deconcept.SWFObjectUtil){return false;}
var _237=deconcept.SWFObjectUtil.getPlayerVersion().major;return(_237>=8)?true:false;},methods:{init:function(){if(!B.flash.el){var o,key,el,cfg=C.flash;el=document.createElement("div");el.id=cfg.div_id;if(document.readyState=="interactive"||document.readyState=="complete"){document.body.appendChild(el);}
o=new SWFObject(this.o.swf_path||cfg.path,cfg.id,cfg.size.w,cfg.size.h,"8");for(key in cfg.args){o.addVariable(key,cfg.args[key]);}
o.write(el);B.flash.el=document.getElementById(cfg.id);}
this.el=B.flash.el;},get:function(key,fn,_239){var val;key=esc(key);val=this.el.get(this.name,key);if(fn){fn.call(_239||this,val!==null,val);}},set:function(key,val,fn,_240){var _241;key=esc(key);_241=this.el.set(this.name,key,val);if(fn){fn.call(_240||this,true,val);}},remove:function(key,fn,_242){var val;key=esc(key);val=this.el.remove(this.name,key);if(fn){fn.call(_242||this,true,val);}}}}};var init=function(){var i,l,b,key,fns=C.methods,keys=C.search_order;for(i=0,l=fns.length;i<l;i++){P.Store.prototype[fns[i]]=empty;}
P.type=null;P.size=-1;for(i=0,l=keys.length;!P.type&&i<l;i++){b=B[keys[i]];if(b.test()){P.type=keys[i];P.size=b.size;for(key in b.methods){P.Store.prototype[key]=b.methods[key];}}}
P._init=true;};P={VERSION:_199,type:null,size:0,add:function(o){B[o.id]=o;C.search_order=[o.id].concat(C.search_order);init();},remove:function(id){var ofs=C.search_order.indexOf(id);if(ofs<0){return;}
C.search_order.splice(ofs,1);delete B[id];init();},Cookie:ec,Store:function(name,o){if(!C.name_re.exec(name)){throw new Error("Invalid name");}
if(!P.type){throw new Error("No suitable storage found");}
o=o||{};this.name=name;o.domain=o.domain||location.hostname||"localhost.localdomain";this.o=o;o.expires=o.expires||365*2;o.path=o.path||"/";this.init();}};init();return P;})();var LOOMIA_PERSIST=new function(){var _245=null;var _246="loomia_persistent_store";var _247=false;return{debugout:function(s){if(_247){try{console.log(this.timestamp()+" "+s);}
catch(e){}}},timestamp:function(){var d=(new Date());var ts=""+d.getHours()+":"+d.getMinutes()+":"+d.getSeconds()+"."+d.getMilliseconds();return ts;},getstore:function(){return _245;},createstore:function(){try{_245=new LOOMIA_PJS.Store(_246);}
catch(e){var msg=(e.message)?e.message:e.description;this.debugout("Error: "+msg);}
this.debugout("Called createstore: pstore: "+_245);},store:function(key,val){this.debugout("Calling store: "+key+", "+val);if(_245){_245.set(key,val);}},get:function(key,_248){this.debugout("fetching: "+key);var _249=null;if(_245){_245.get(key,_248);}},remove:function(key,_250){if(_250==null){_250=function(ok,val){};}
if(_245){_245.remove(key,_250);}}};}();function _objToJSON(o){this.object=o;}
function _arrayToJSON(o){this.array=o;}
(function(){var m={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r","\"":"\\\"","\\":"\\\\"},s={array:function(x){var a=["["],b,f,i,l=x.length,v;for(i=0;i<l;i+=1){v=x[i];f=s[typeof v];if(f){v=f(v);if(typeof v=="string"){if(b){a[a.length]=",";}
a[a.length]=v;b=true;}}}
a[a.length]="]";return a.join("");},"boolean":function(x){return String(x);},"null":function(x){return"null";},number:function(x){return isFinite(x)?String(x):"null";},object:function(x){if(x){if(x instanceof Array){return s.array(x);}
var a=["{"],b,f,i,v;for(i in x){v=x[i];f=s[typeof v];if(f){v=f(v);if(typeof v=="string"){if(b){a[a.length]=",";}
a.push(s.string(i),":",v);b=true;}}}
a[a.length]="}";return a.join("");}
return"null";},string:function(x){if(/["\\\x00-\x1f]/.test(x)){x=x.replace(/([\x00-\x1f\\"])/g,function(a,b){var c=m[b];if(c){return c;}
c=b.charCodeAt();return"\\u00"+Math.floor(c/16).toString(16)+(c%16).toString(16);});}
return"\""+x+"\"";}};_objToJSON.prototype.toJSONString=function(){return s.object(this.object);};_arrayToJSON.prototype.toJSONString=function(){return s.array(this.array);};})();function toJSONString(obj){if(obj instanceof Array){return(new _arrayToJSON(obj)).toJSONString();}
return(new _objToJSON(obj)).toJSONString();}
var LOOMIA_POST=new function(){return{toQueryString:function(s){return encodeURIComponent(s);},toJSONString:function(s){return toJSONString(s);},securify:function(url){return url.replace(/^http:/,"https:").replace(/:[0-9]+/,"");},pingserver:function(url){LOOMIA_DEBUG.debug("pinging server: "+url);var img=new Image(1,1);img.onload=function(){};img.onerror=function(){};img.src=url;return img;}};};var LOOMIA_CLIX=new function(){var _255=true;var _256=1000;var _257=["current_url","action_ts","arrival_ts","methodName","onload","publisher_key","tagname","url","xmethod","referrer","click_x","click_y","widget_coords","canvas_x","canvas_y"];var _258=LOOMIA_C.CLICKSTREAM_SERVER;var _259;var lcm;var isIE=(navigator.userAgent.toLowerCase().indexOf("msie")>-1);var _262=0;var _263=0;function getAbsolutePosition(_264){var r={x:_264.offsetLeft,y:_264.offsetTop};if(_264.offsetParent){var tmp=getAbsolutePosition(_264.offsetParent);r.x+=tmp.x;r.y+=tmp.y;}
return r;}
function getPosition(e){e=e||window.event;var _267={x:0,y:0};if(e.pageX||e.pageY){_267.x=e.pageX;_267.y=e.pageY;}else{_267.x=e.clientX+(document.documentElement.scrollLeft||document.body.scrollLeft)-document.documentElement.clientLeft;_267.y=e.clientY+(document.documentElement.scrollTop||document.body.scrollTop)-document.documentElement.clientTop;}
return _267;}
function getElementCoordinates(el){var _268=0,widget_y=0,widget_bx=0,widget_by=0;if(el){top_left=getAbsolutePosition(el);_268=top_left.x;widget_y=top_left.y;height=isNaN(parseInt(el.clientHeight))?0:parseInt(el.clientHeight);width=isNaN(parseInt(el.clientWidth))?0:parseInt(el.clientWidth);widget_bx=_268+width;widget_by=widget_y+height;}
return[_268,widget_y,widget_bx,widget_by];}
function getWidgetCoordinates(){var _269=[];var _270=[];var d;if(window.LOOMIA){widgets=LOOMIA.getWidgets();for(var i=0;i<widgets.length;i++){var w=widgets[i];d=document.getElementById(w.anchor);if(d){_269.push(d);}}}else{var _272=LOOMIA_C.display_div;if(LOOMIA_CLIX.my_params&&LOOMIA_CLIX.my_params.anchor){_272=LOOMIA_CLIX.my_params.anchor;}
d=document.getElementById(_272);if(d){_269.push(d);}}
for(var i=0;i<_269.length;i++){_270.push(getElementCoordinates(_269[i]));}
if(_270.length==0){_270=[0,0,0,0];}
return _270;}
function getCanvasSize(){var _273=0;var _274=0;if(document.compatMode=="CSS1Compat"||isIE){_273=document.body.clientHeight;_274=document.body.clientWidth;}else{_273=document.documentElement.clientHeight;_274=document.documentElement.clientWidth;}
return{"height":_273,"width":_274};}
function getLastXY(){return{"click_x":_262,"click_y":_263};}
function _loomiaClickMonitor(_275,_276,puid,guid){LOOMIA_DEBUG.debug("clixbase:_loomiaClickMonitor: instatiating LCM with params server="+_275+" pub_key="+_276+" puid="+puid+" guid="+guid);this.loomia_server=_275;this.current_url=window.location.href;this.referrer=document.referrer;this.arrival_ts=(new Date()).getTime();this.publisher_key=_276;this.puid=puid;this.guid=guid;this.cshandler=function(e){LOOMIA_DEBUG.debug("clixbase:_loomiaClickMonitor:cshandler called with event="+e);if(e&&e.srcElement){var _279=e.srcElement;}else{var _279=e?e.target:null;}
var data={};data["action_ts"]=(new Date()).getTime();if(e){this._collectData(_279,e,data);}else{data["onload"]=1;}
if(e){try{coords=getPosition(e);_262=data["click_x"]=coords.x;_263=data["click_y"]=coords.y;}
catch(e){}}
data["widget_coords"]=toJSONString(getWidgetCoordinates());var _281=getCanvasSize();data["canvas_x"]=_281.width;data["canvas_y"]=_281.height;data["current_url"]=this.current_url;data["referrer"]=this.referrer;data["arrival_ts"]=this.arrival_ts;data["publisher_key"]=this.publisher_key;data["methodName"]="addClickstream";var s=this._printArray(data,_257,"&");var _282=this.loomia_server+"?"+s;var _283=LOOMIA_UTILS.getCookie(LOOMIA_C.CLIENT_TRACKING_COOKIE);if(_283){_282=_282+"&ctrack="+_283;}
if(!this.puid){this.puid=LOOMIA_UTILS.getCookie(LOOMIA_C.PUID_COOKIE);}
if(this.puid){_282=_282+"&puid="+this.puid;}
if(this.guid){this.encoded_guid=encodeURIComponent(this.guid);_282=_282+"&guid="+this.encoded_guid;}
LOOMIA_CLIX.click_url=_282;if(data["onload"]!=1){LOOMIA_CLIX.pingserver(0);}
return data;};this._printArray=function(arr,_285,_286){if(!_286){_286="\n";}
var _287=[];for(var i=0;i<_285.length;i++){var key=_285[i];var _288=arr[key];if(!_288||typeof _288=="undefined"){continue;}
if(key=="xmethod"){key="method";}
if(key=="url"||key=="current_url"||key=="referrer"){var benc=Base64.encode(decodeURIComponent(_288));_287[_287.length]=key+"="+benc;}else{_287[_287.length]=key+"="+encodeURIComponent(_288);}}
var s=_287.join(_286);return s;};this._searchForAncestor=function(_289,_290){if(!_289){return null;}
if(_289.tagName==_290){return _289;}
if(_289.tagName=="HTML"||_289.tagName=="BODY"||_289.tagName=="HEAD"){return null;}
return this._searchForAncestor(_289.parentNode,_290);};this._getRelevantAncestor=function(_291,_292){if(!_291){return null;}
if(!_292){return null;}
var _293=_291.tagName;var _294=_292.type;if(!_293){return null;}
var data={};switch(_293){case"A":return _291;case"BODY":case"HTML":return null;break;case"INPUT":var _295=_291.parentNode;if(_295.tagName=="FORM"){return _295;}
return this._searchForAncestor(_291,"A");break;case"FORM":if(_294=="submit"){return _291;}
break;default:ancestor=this._searchForAncestor(_291,"A");return ancestor;break;}
return null;};this._collectData=function(_296,_297,data){if(!_296){return null;}
if(!_297){return null;}
var _298=_297.type;var _299=this._getRelevantAncestor(_296,_297);if(!_299){return null;}
var _300=_299.tagName;if(!_300){return null;}
data["tagname"]=_300;switch(_300){case"A":data["url"]=_299.href;break;case"FORM":data["url"]=_299.action;data["xmethod"]=_299.method;break;default:break;}
return data;};}
return{DROP_IFRAME:_255,click_url:null,DELAY_ON_CLICK:_256,getLastXY:getLastXY,getWidgetCoordinates:getWidgetCoordinates,getCanvasSize:getCanvasSize,my_params:_259,lcm:lcm,perUID:null,init:function(obj){LOOMIA_DEBUG.debug("clixbase.js:init - initializing clickstream rececorder with params:"+toJSONString(obj));if(obj==null){return;}
if(LOOMIA_CLIX.lcm){LOOMIA_DEBUG.debug("clixbase.js:init - LCM already defined. exiting.");return;}
var puid=null;if(typeof obj.publisher_key=="undefined"){LOOMIA_DEBUG.debug("No publisher key. Exiting");return;}
if(typeof obj.userid!="undefined"&&obj.userid){puid=obj.userid;}
LOOMIA_CLIX.loadPersistentUID();if(LOOMIA_CLIX.DROP_IFRAME){LOOMIA_CLIX.dropIFrame();}
LOOMIA_CLIX._loomiaTrack(obj,puid);LOOMIA_UTILS.execute_when_present(function(){LOOMIA_CLIX.pingserver(_256);},LOOMIA_LOADIFRAME.IFRAME_ID);},pingserver:function(_301){var url=this.click_url;function post(){if(LOOMIA_CLIX.perUID){var _302=encodeURIComponent(LOOMIA_CLIX.perUID);url=url+"&peruid="+_302;}else{LOOMIA_DEBUG.debug("perUID NOT FOUND!");}
LOOMIA_POST.pingserver(url);}
LOOMIA_DEBUG.debug("Starting timeout of "+_301+" for click to: "+this.click_url);setTimeout(post,_301);},loadPersistentUID:function(){if(this.perUID){LOOMIA_DEBUG.debug("Already have a perUID"+this.perUID);return;}
LOOMIA_DEBUG.debug("clixbase: Calling createStore in loadPersistentUID.");LOOMIA_PERSIST.createstore();function generatePersistentUID(ok,val){LOOMIA_DEBUG.debug("clixbase: generatePersistentUID="+val);var uid=LOOMIA_UTILS.randomUsername();if(val==null||val==""){val=uid;}
LOOMIA_DEBUG.debug("Storing: "+val);LOOMIA_PERSIST.store("PerUID",val);LOOMIA_CLIX.perUID=val;}
LOOMIA_PERSIST.get("PerUID",generatePersistentUID);},dropIFrame:function(){LOOMIA_DEBUG.debug("clixbase.js: Calling dropIFrame.");function writeiframe(){LOOMIA_LOADIFRAME.writeIFrame(LOOMIA_CLIX.perUID);LOOMIA_LOADIFRAME.setSrc();}
LOOMIA_UTILS.execute_when_loaded(writeiframe,"LOOMIA_CLIX.perUID",20);},_loomiaTrack:function(obj,puid){LOOMIA_DEBUG.debug("clixbase:_loomiaTrack: Creating new LCM. puid="+puid+" obj="+toJSONString(obj));LOOMIA_CLIX.my_params=obj;if(typeof publisher_key=="undefined"){var _304="";}
if(_304==""){var _304=obj.publisher_key;}
if(typeof obj.guid=="undefined"){obj.guid=null;}
lcm=new _loomiaClickMonitor(_258,_304,puid,obj.guid);this.h=function(e){if(!e){e=window.event;}
var d=lcm.cshandler(e);};this.addEventHandlerToObject=function(_305,func,_306){if(_306==null){_306=window;}
var old=_306[_305];if(typeof _306[_305]!="function"){_306[_305]=func;}else{_306[_305]=function(e){old(e);func(e);};}};if(isIE){this.addEventHandlerToObject("onclick",this.h,document);}else{window.addEventListener("click",this.h,true);}
LOOMIA_DEBUG.debug("clixbase:_loomiaTrack: Calling cshandler on pageload");var d=lcm.cshandler(null);this.lcm=lcm;return true;}};};var LOOMIA_LOADIFRAME=new function(){var _308=LOOMIA_C.JS_PATH+"setcookie.html";var _309="__loomia_cs_iframe_anchor__";var _310="__loomia_cs_iframe__";function getIFrameDocument(_311){var _312=null;try{if(_311.contentDocument){_312=_311.contentDocument;}else{if(_311.contentWindow){_312=_311.contentWindow.document;}else{if(_311.document){_312=_311.document;}}}}
catch(e){var msg=(e.message)?e.message:e.description;LOOMIA_UTILS.debugout(msg);}
return _312;}
return{IFRAME_ID:_310,createAnchor:function(){document.write("<div id=\""+_309+"\"></div>");},setSrc_wait:function(){LOOMIA_UTILS.debugout("Calling setSrc_wait.");var ss=this.setSrc;function func(){ss();}
LOOMIA_UTILS.execute_when_present(func,_310);},setSrc:function(){LOOMIA_UTILS.debugout("Calling setSrc.");var _314=document.getElementById(_310);var _315=null;if(_314){_315=getIFrameDocument(_314);if(_315){try{LOOMIA_UTILS.debugout("Trying to set iframe.src: "+_308);_315.location.replace(_308);LOOMIA_UTILS.debugout("Set iframe.src: "+_308);}
catch(e){var msg=(e.message)?e.message:e.description;LOOMIA_UTILS.debugout(msg);}}}},createIFrame:function(name){var _316=null;var isIE=(navigator.userAgent.toLowerCase().indexOf("msie")>-1);if(!isIE){_316=document.createElement("IFRAME");if(name){_316.name=name;}}else{if(name){create_tag="<iframe name='"+name+"'></iframe>";}else{create_tag="<iframe></iframe>";}
_316=document.createElement(create_tag);}
_316.height="0";_316.width="0";_316.style.border="0";_316.id=_310;return _316;},writeIFrame:function(uid){LOOMIA_DEBUG.debug("loadiframe: calling writeIFrame uid="+uid);var _317=LOOMIA_LOADIFRAME.createIFrame(uid);var anc=document.body;try{anc.appendChild(_317);}
catch(e){LOOMIA_DEBUG.debug("Error appending IFrame");}}};};function loomiaDomFunction(f,a){var n=0;var t=setInterval(function(){var c=true;n++;if(typeof document.getElementsByTagName!="undefined"&&(document.getElementsByTagName("body")[0]!=null||document.body!=null)){c=false;if(typeof a=="object"){for(var i in a){if((a[i]=="id"&&document.getElementById(i)==null)||(a[i]=="tag"&&document.getElementsByTagName(i).length<1)){c=true;break;}}}
if(!c){f();clearInterval(t);}}
if(n>=60){clearInterval(t);}},250);}
function loomia_clickstreamRecorder(obj,_319){if(window.attachEvent){window.attachEvent("onload",function(){LOOMIA_CLIX.init(obj);});}else{LOOMIA_DEBUG.debug("clixdom:loomia_clickstreamRecorder --  Setup DOM-ready call to clickstream recorder");var _320=new loomiaDomFunction(function(){LOOMIA_CLIX.init(obj);});}}
if(window.L_VARS){var loomia_doclickstream=function(){LOOMIA_CLIX.init(L_VARS);};if(window.attachEvent){if(document.readyState!="complete"){window.attachEvent("onload",loomia_doclickstream);}else{loomia_doclickstream();}}else{var loomia_cr=new loomiaDomFunction(loomia_doclickstream);}}